### ISSUE TITLE
Support dual boot

### ISSUE THREAD

**Issue by coolcoder613eb** [mikaku/Fiwix#37]
I would like to be able to dual boot Fiwix with other operating systems,
this will involve changing the installer to allow installing already made partitions,
and keeping /boot on the same partition.
Also, instructions for the GRUB entry would be helpful.

**Comment by mikaku** [comment]
The following is the new version of `install.sh` Bash script where you can choose to install FiwixOS on a separate partition, and also if you want to install GRUB or not at the end of the installation:

[install.txt](https://github.com/mikaku/Fiwix/files/12185630/install.txt)

(rename it as `install.sh`, since GitHub does not support to upload `.sh` files)

How to use this file:
-

You have two possible options:

- Generate again the Installation CD-ROM, substituting the original `install.sh` by this one.
  - Proceed with a normal installation.

or

- Create a simple floppy disk formatted with an Ext2 filesystem (revision level 0 and without any features).
  - Mount the floppy disk in your system and copy this script on it, (then `umount` the floppy disk).
  - Execute `debugfs -w /dev/fd0` and set the revision level to 0 and remove any features.
  - Boot with the original FiwixOS 3.2 Installation CD-ROM.
  - Before start installation, mount the floppy disk (`mount -t ext2 /dev/fd0 /mnt/floppy`).
  - Start the installation executing the new script instead of executing the original script in the CD-ROM (`/mnt/floppy/install.sh`).

**Comment by coolcoder613eb** [comment]
when I try to boot it with grub2 on my computer, it just goes to a screen with a blinking cursor forever

**Comment by mikaku** [comment]
Your information is vague.

Fiwix supports Multiboot Specification 1, so as long as your GRUB2 also supports it, then it's just a matter to have the correct configuration.

**Comment by mikaku** [comment]
Closing due to no response for two weeks.

If you still need more information, please add a comment and the issue can be reopened.

**Comment by coolcoder613eb** [comment]
Would it be possible to build Fiwix with GRUB2?

**Comment by mikaku** [comment]
GRUB2 is just a bootloader, as long as it supports Multiboot Specification v1, then it will be able to boot Fiwix.
